name: flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  go_router: ^15.1.2
  shared_preferences: ^2.5.3
  lottie: ^2.6.0
  geolocator: ^14.0.1
  http: ^1.1.0
  google_fonts: ^6.2.1
  flutter_compass: ^0.8.0
  sensors_plus: ^4.0.2
  image_picker: ^1.0.0
  permission_handler: ^11.0.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/languages/
    - assets/motions/
    - assets/motions/loading.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/T.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/T.png"
